### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by topsolutionsltd** [t3ko/dpd-pl-api-php#13]
```
$ composer require t3ko/dpd-pl-api-php php-http/curl-client:^1
Using version ^0.3.0 for t3ko/dpd-pl-api-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.4.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpro/soap-client 0.6.0 requires symfony/console ~2.8|~3.0 -> no matching package found.
    - t3ko/dpd-pl-api-php 0.3 requires phpro/soap-client 0.6.0 -> satisfiable by phpro/soap-client[0.6.0].
    - Installation request for t3ko/dpd-pl-api-php ^0.3.0 -> satisfiable by t3ko/dpd-pl-api-php[0.3].
```

Najnowsza wersja phpro/soap-client to 1.3.1 a po jej zainstalowaniu niestety pakiet nadal domaga się wersji 0.6.0.

**Comment by t3ko** [comment]
Nie testowałem biblioteki z `phpro/soap-client` innym niż `0.6.0` dlatego tak jest wskazane w `composer.json`. 
Problemem jest tu oczywiście stara wersja `symfony/console` której wymaga `phpro/soap-client` (najwyżej `3.0`)  a jednocześnie obejmujący projekt ma wymaganie na pakiety symfony co najmniej `4.4`.

Przetestuje w ciągu najbliższych dni podbicie `phpro/soap-client` do wyższej wersji i dam znać.

**Comment by Lechapp** [comment]
Jest szansa na podniesienie wersji? phpro/soap-client jest już w wersji 1.4.1, natomiast symfony w 5.2.1. Chciałbym spróbować Twojej biblioteki ale jej implementacja wymaga symfony w wersji 3.0, a tworząc nowy projekt jest to raczej nieakceptowalne.

**Comment by mkurzeja** [comment]
Cześć, przygotowałem forka i podbiłem wersję. https://github.com/mkurzeja/dpd-pl-api-php - testy przechodzą, zobaczę w najbliższych dniach czy w praktyce też wszystko działa i ew. zgłoszę pull request.
