### ISSUE TITLE
 Class 'Http\Discovery\HttpClientDiscovery' not found in

### ISSUE THREAD

**Issue by piotrpog** [t3ko/dpd-pl-api-php#15]
Gdy próbuję użyć metody `generatePackageNumbers`, pokazuej się ten błąd:

Fatal error: Uncaught Error: Class 'Http\Discovery\HttpClientDiscovery' not found in C:\xampp741\htdocs\test2\vendor\phpro\soap-client\src\Phpro\SoapClient\Soap\Handler\HttPlugHandle.php:54 Stack trace: #0 C:\xampp741\htdocs\test2\vendor\t3ko\dpd-pl-api-php\src\Api.php(245): Phpro\SoapClient\Soap\Handler\HttPlugHandle::createWithDefaultClient() #1 C:\xampp741\htdocs\test2\vendor\t3ko\dpd-pl-api-php\src\Api.php(200): T3ko\Dpd\Api->obtainClient('T3ko\\Dpd\\Soap\\C...') #2 C:\xampp741\htdocs\test2\vendor\t3ko\dpd-pl-api-php\src\Api.php(456): T3ko\Dpd\Api->obtainPackageServiceClient() #3 C:\xampp741\htdocs\test2\index.php(31): T3ko\Dpd\Api->generatePackageNumbers(Object(T3ko\Dpd\Request\GeneratePackageNumbersRequest)) #4 {main} thrown in C:\xampp741\htdocs\test2\vendor\phpro\soap-client\src\Phpro\SoapClient\Soap\Handler\HttPlugHandle.php on line 54

Mój kod:

```

error_reporting(E_ALL);
ini_set('display_errors', '1');

require_once __DIR__.'/vendor/autoload.php';
use \T3ko\Dpd\Request\GeneratePackageNumbersRequest;
use T3ko\Dpd\Objects\Sender;
use T3ko\Dpd\Objects\Receiver;
use T3ko\Dpd\Objects\Parcel;
use T3ko\Dpd\Objects\Package;

// usunięto dane
$login = '';
$password = '';
$fid = ;

$api = new \T3ko\Dpd\Api($login, $password, $fid);
$api->setSandboxMode(true);

$sender = new Sender(12345, 501100100, 'Jan Kowalski', 'Puławska 1', '02566', 'Warszawa', 'PL');
$receiver = new Receiver(605600600, 'Piotr Nowak', 'Kwiatowa 2', '60814', 'Poznań', 'PL');

$parcel = new Parcel(30, 30, 15, 1.5);

$package = new Package($sender, $receiver, [$parcel]);

$singlePackageRequest = GeneratePackageNumbersRequest::fromPackage($package);

$response = $api->generatePackageNumbers($singlePackageRequest);

```

**Comment by t3ko** [comment]
Wygląda jak problem z klientem HTTP a nie samą biblioteką. W jakiej wersji zainstalowała się pseudo-paczka `psr/http-client-implementation` ?

**Comment by piotrpog** [comment]
Zakładam że nie chodzi ci konkretnie o `psr/http-client-implementation` która nie istnieje, tylko o jej odpowiednik?

Próbowałem tego:

```
        "php-http/guzzle6-adapter": "2.0",
        "guzzlehttp/guzzle": "~6.0",
        "t3ko/dpd-pl-api-php": "^0.3.0"
```
Oraz tego:
```
        "guzzlehttp/guzzle": "^7.2",
        "php-http/guzzle7-adapter": "^0.1.1",
        "t3ko/dpd-pl-api-php": "^0.3.0"
```

Próba użycia wersji `php-http/guzzle6-adapter` w wersji `^1.0` wywoływała błąd composera.

**Comment by t3ko** [comment]
Zależności zostały nieco wyczyszczone w najnowszej wersji  `0.4`. 
Daj znać proszę czy wciąż masz problem.

**Comment by t3ko** [comment]
Zamykam
