### ISSUE TITLE
Śledzenie przesyłek

### ISSUE THREAD

**Issue by buzzard10** [t3ko/dpd-pl-api-php#2]
Hej,
kiedy planujesz ogarnąć śledzenie przesyłek? :)

**Comment by t3ko** [comment]
Cześć, Niestety mało czasu mam na cokolwiek. Po merge'u brancha ze zlecaniem odbioru przesyłek biorę się za tracking. Zapraszam do contributingu :)

**Comment by buzzard10** [comment]
Dzięki wielkie za wiadomość! 
Jesteś w stanie mi powiedzieć kiedy w pełni będzie zrobiony moduł rejestracji przesyłki? Tj. zarówno przesył danych + generowanie etykiet? 
Czy z tego co jest napisane teraz mogę jakoś generować zlecenia odbioru? Mam na myśli tą dodatkową usługę DPD, która pozwala zlecić wygenerowanie paczki + odbiór z wydrukiem etykiety przez kuriera na następny dzień :) 
O ta usługa: https://i.imgur.com/yumSf9x.png

**Comment by t3ko** [comment]
Rejestracja przesyłki i drukowanie etykiety już jest gotowe w masterze.
Zlecanie odbioru mam w zasadzie gotowe i u mnie produkcyjnie działa - ale muszę dopisać trochę testów i dokumentacji żeby nadawało się to do merge'a.

**Comment by buzzard10** [comment]
jej, ekstra ! :) 
Ja sobie już tracking ogarnąłem :) Będziesz tak miły i dasz znać jak będzie zlecenie odbioru gotowe ? :)

**Comment by t3ko** [comment]
Tak, dowiążę ten issue do PR-a z kodem zlecenia odbioru, więc dostaniesz powiadomienie jak trafi do mastera.

**Comment by buzzard10** [comment]
Dzięki wielkie! Nie mogę się doczekać! :)

**Comment by manickus** [comment]
Czy zlecenie odbioru jest juz dostepne?

**Comment by t3ko** [comment]
Tak! 
https://github.com/t3ko/dpd-pl-api-php/releases/tag/0.2
