### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by kamilsu** [t3ko/dpd-pl-api-php#6]
Hej
Klasa wygląda fajnie. Nie mogę jej jednak zainstalować.  Co może być przyczyną?

>  composer require t3ko/dpd-pl-api-php
Using version ^0.2.0 for t3ko/dpd-pl-api-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for t3ko/dpd-pl-api-php ^0.2.0 -> satisfiable by t3ko/dpd-pl-api-php[0.2].
    - t3ko/dpd-pl-api-php 0.2 requires php-http/client-implementation ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by t3ko** [comment]
Biblioteka korzysta z `httplug`a jako abstrakcji klienta HTTP i nie zawiera żadnej domyślnej implementacji. Po stronie projektu, w którym jest umieszczona - leży obowiązek dostarczenia klienta HTTP zgodnego z 'PSR-18'. Więcej info tutaj: [http://docs.php-http.org/en/latest/httplug/users.html](http://docs.php-http.org/en/latest/httplug/users.html)
Rzeczywiście README o tym nie wspomina - moje przeoczenie - do poprawki.

Jeśli masz `curl`a to powinno zadziałać tak:
`composer require t3ko/dpd-pl-api-php php-http/curl-client:^1`

Jeśli zamiast tego wolisz np. Guzzle'a jako klienta http to:
`composer require t3ko/dpd-pl-api-php pphp-http/guzzle6-adapter:^1 guzzlehttp/guzzle:~6.0`

Pełna lista adapterów do znanych klientów HTTP tutaj:
[http://docs.php-http.org/en/latest/clients.html](http://docs.php-http.org/en/latest/clients.html)

**Comment by kamilsu** [comment]
Dzięki
